name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Install required SDK components
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          yes | sdkmanager --licenses

      - name: Point local.properties to SDK
        run: |
          echo "sdk.dir=${ANDROID_SDK_ROOT}" > local.properties
          cat local.properties

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      # ➜ Mode verbeux pour voir l'erreur exacte
      - name: Build Debug APK
        run: ./gradlew --no-daemon --stacktrace --info --warning-mode=all clean assembleDebug

      # ➜ On récupère TOUJOURS les rapports (même si ça échoue)
      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-reports
          path: |
            build/reports/**
            app/build/reports/**
            **/reports/problems/**

      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: MikaPEA-debug-apk
          path: app/build/outputs/**/debug/*.apk
