name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - run: chmod +x ./gradlew
      - run: ./gradlew --no-daemon --stacktrace clean assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: MikaPEA-debug-apk
          path: app/build/outputs/apk/debug/*.apk
